### PR TITLE
admin/netdata: enable Netdata Cloud

### LINKED ISSUE #710: admin/netdata: enable cloud
<https://github.com/immortalwrt/packages/blob/e62fc0d3b11ca2dff5d17bc8e54dcbc59f68020c/admin/netdata/Makefile#L66>

The cloud feature is removed in upstream OpenWrt, "due to package size concerns".

I personally don't think this is an issue on ImmortalWrt. Can we enable this (or add a seperate package for cloud-agent usage only)?

### PR DESCRIPTION
**Pull request by mochaaP**
Close #710

### CODE REVIEW

**Comment by 1715173329** [comment]
I'd say netdata is just a resources waster... But this patch LGTM. Will merge it once CI passed.

**Comment by 1715173329** [comment]
Looks like it fails

**Comment by mochaaP** [comment]
Working on it.

**Comment by 1715173329** [comment]
i don't know what the heck they made in their release tarball, building from their github source works prettry well
those 2 patches are not required, but let's included them anyway - remove warnings

**Comment by mochaaP** [comment]
All test passed, ready for review :)

**Comment by zcluo** [comment]
优秀。。我直接第一次引导后离线装最新。这个方便

**Comment by 1715173329** [comment]
Merged, thanks!

**Pull request merged**
