### PR TITLE
adguardhome: Update to 0.107.39

### PR DESCRIPTION
**Pull request by MkQtS**
Compile and run tested on x64, 23.05 branch

### CODE REVIEW

**Comment by 1715173329** [comment]
Looks like Go 1.21 doesn't like this change...

**Comment by 1715173329** [comment]
Please bump to v0.107.39

**Comment by MkQtS** [comment]
updated but not tested

**Comment by MkQtS** [comment]
I don't think I can fix this, maybe wait for AdGuardHome updating go version...

**Comment by 1715173329** [comment]
Fine, thank you anyway ;)

**Pull request closed without merging**
