### PR TITLE
dockerd: generate network config with "device" options

### PR DESCRIPTION
**Pull request by swirly0p**
Because OP master replace "ifname" with "device" , dockerd.init must be changed.

### CODE REVIEW

**Comment by 1715173329** [comment]
Could you submit this patch to upstream OpenWrt?

**Comment by swirly0p** [comment]
> Could you submit this patch to upstream OpenWrt?

Ok , i will try

**Comment by swirly0p** [comment]
openwrt/packages#15788

**Comment by 1715173329** [comment]
> [openwrt/packages#15788](https://github.com/openwrt/packages/pull/15788)

This one is not standard. See CONTRIBUTING.md

**Pull request closed without merging**
